### ISSUE TITLE
[Fix] - Change Default Configuration File Location on Linux

### ISSUE THREAD

**Issue by virajsazzala** [virajsazzala/theatre-cli#1]
I propose changing the default configuration file location for "theatre-cli" on Linux machines to `~/.config/theatre-cli/config.json`. Currently, the configuration file is created in a different location, and this change aims to follow standard Linux practices for configuration files.

## Motivation
The motivation behind this feature request is to adhere to established conventions on Linux systems. Placing configuration files in `~/.config` aligns with the Filesystem Hierarchy Standard (FHS) and makes it easier for users to find and manage their configuration settings.

## Use Case
Linux users often expect configuration files to be stored in `~/.config`, as it's a well-known location for application-specific settings. This change will improve the user experience for "theatre-cli" users on Linux by conforming to this convention.

## Current Behavior
Currently, the configuration file for "theatre-cli" is created in the home directory, which may not align with Linux standards.

## Proposed Behavior
With this feature, "theatre-cli" will create its configuration file at `~/.config/theatre-cli/config.json` by default on Linux systems. This standardized location will make it more intuitive for users to locate and manage their configuration settings.

**Comment by lexcsam** [comment]
@virajsazzala hey , can I work on this issue , if yes , please assign it to me.

**Comment by virajsazzala** [comment]
@lexcsam Thanks for looking into this! I'll assign it to you.
