### ISSUE TITLE
[Docs] - Add documentation for the codebase

### ISSUE THREAD

**Issue by virajsazzala** [virajsazzala/theatre-cli#2]
It's always great to have documentation about the codebase, as it would help new developers and contributors to the project!

It would be great to have a `docs/` directory and having documentation neatly structured for the entire repository!

These are the primary files for which documentation is required:
- `theatre_cli/movie.py`
- `theatre_cli/player.py`
- `theatre_cli/config.py`
- `scripts/theatre-cli`

How to structure the `docs/` directory? -> It's upto you, just keep it clean!

Also, in addition to this, a brief introduction to rest of the files and the file structure, would be greatly appreciated!

**Comment by nayanmapara** [comment]
Hey @virajsazzala I would like to work on this.

**Comment by virajsazzala** [comment]
Yes @nayanmapara, you can get started!

**Comment by Nitish36** [comment]
Hey @virajsazzala I would like to work on the documentation part.

**Comment by virajsazzala** [comment]
Yes @Nitish36! You can get started too
