### ISSUE TITLE
[Feature Request] - Update default movie/shows folder location

### ISSUE THREAD

**Issue by virajsazzala** [virajsazzala/theatre-cli#4]
As of now, the default location to find movies and shows is set during the initial setup. It can be changed only if you find and edit the config file on your computer. 

Instead, can we add a flag to the command, something like `theatre-cli --update-dir [PATH]`, to update the path instead.

**Comment by CarbonNeuron** [comment]
I'd like to work on this issue, can you assign it to me?

**Comment by CarbonNeuron** [comment]
Sorry for working on this when I was not assigned to it, Just thought it would be an easy fix and it was.

**Comment by virajsazzala** [comment]
Thanks for looking into this @CarbonNeuron! It's totally okay, I'll take a look at your PR
