### ISSUE TITLE
[Feature Request] -  Recursive listing of movies/shows

### ISSUE THREAD

**Issue by virajsazzala** [virajsazzala/theatre-cli#5]
As of now, the video files in the default setup folder are displayed for selection and playing. But there are cases where people have directories under the default setup folder, and so on. 

So, can we display not just the video in the default setup folder, but every single video under every directory under the default setup folder?

**Comment by Vivy24** [comment]
Hi Virajsazzala, can I work on this issue?

**Comment by virajsazzala** [comment]
Yes @Vivy24, You can get started!

**Comment by Vivy24** [comment]
Sure! I will work on it during this weekend
